services:
  stac-fastapi-geoparquet:
    container_name: stac-fastapi-geoparquet
    build: .
    environment:
      - STAC_FASTAPI_GEOPARQUET_HREF=/app/data/naip.parquet
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    ports:
      - 8000:8000
    volumes:
      - ./data:/app/data