site_name: stac-fastapi-geoparquet
site_url: https://stac-utils.github.io/stac-fastapi-geoparquet/
site_author: Pete Gadomski
repo_url: https://github.com/stac-utils/stac-fastapi-geoparquet/
repo_name: stac-utils/stac-fastapi-geoparquet

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/developmentseed"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/development-seed"

theme:
  name: material
  logo: assets/logo_no_text.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: default
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: default
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - overrides/stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
