#!/usr/bin/env python3

import asyncio
import json
from pathlib import Path

import pystac.utils
import rustac

DATA_PATH = Path(__file__).parents[1] / "data"
OUTPUT_PATH = DATA_PATH / "collections.json"


async def main() -> None:
    collections = []
    for href in DATA_PATH.glob("*.parquet"):
        items = await rustac.read(str(href))
        collection = rustac.collection_from_id_and_items(
            Path(href).stem, items["features"]
        )
        collection["links"] = []
        collection["assets"] = {
            "data": {
                "href": pystac.utils.make_relative_href(
                    str(Path(href).absolute()), OUTPUT_PATH
                ),
                "type": "application/vnd.apache.parquet",
            }
        }
        collections.append(collection)

    with open(OUTPUT_PATH, "w") as f:
        json.dump(collections, f, indent=2)


if __name__ == "__main__":
    asyncio.run(main())
