name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    env:
      DUCKDB_LIB_DIR: /opt/duckdb
      LD_LIBRARY_PATH: /opt/duckdb
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint
        run: scripts/lint
      - name: Test
        run: scripts/test
      - name: Validate
        run: scripts/validate
      - name: Build docs
        run: uv run mkdocs build --strict
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        if: ${{ github.ref == 'refs/heads/main' && matrix.python-version == '3.11' }}
        with:
          path: site/
  deploy-docs:
    name: Deploy docs
    needs: lint-and-test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
        id: deployment
